# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_core', '0003_auto_20171022_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, b'Diproses'), (2, b'Dibatalkan'), (3, b'Ditahan'), (4, b'Selesai')], default=1),
        ),
    ]
