# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_core', '0004_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_core_sale_checkout', to='pos_core.Checkout'),
        ),
    ]
